/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const componentsCategories = {
  Basic: 'basic',
  Form: 'form',
  Overlays: 'overlays',
  Layout: 'layoutsAndTemplates',
  Incubator: 'incubator'
};

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}]

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: `getting-started`
        }
      ]
    },
    {
      type: 'category',
      label: 'Foundation',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: `foundation`
        }
      ]
    },
    {
      type: 'category',
      label: 'Components',
      collapsible: false,
      items: ['Basic', 'Form', 'Overlays', 'Layout', 'Native', 'Incubator'].map(category => {
        return {
          type: 'category',
          label: category,
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: `components/${componentsCategories[category]}`
            }
          ]
        };
      })
    }
  ]
};
