/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const componentsCategories = {
  // foundation: 'Foundation',
  // assets: 'Assets',
  navigation: 'Navigation',
  layout: 'Layout',
  controls: 'Controls',
  status: 'Status',
  media: 'Media',
  lists: 'Lists',
  form: 'Form',
  dateTime: 'Date & Time',
  overlays: 'Overlays',
  charts: 'Charts',
  incubator: 'Incubator',
  infra: 'Infra'
};

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}]

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: `getting-started`
        }
      ]
    },
    {
      type: 'category',
      label: 'Foundation',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: `foundation`
        }
      ]
    },
    {
      type: 'category',
      label: 'Components',
      collapsible: false,
      // items: ['Basic', 'Lists', 'Form', 'Overlays', 'Layout', 'Keyboard', 'Incubator'].map(category => {
      items: Object.keys(componentsCategories).map(category => {
        return {
          type: 'category',
          label: componentsCategories[category],
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: `components/${category}`
            }
          ]
        };
      })
    }
  ]
};
