// import {Constants} from '../../src';
export const navigationData = {
  Style: [
    {title: 'Typography', tags: 'fonts text', screen: 'example.style.TypographyScreen'},
    {title: 'Border Radius', tags: 'corener border radius circle', screen: 'example.style.BorderRadiusesScreen'},
    {title: 'Colors', tags: 'palette rgb hex', screen: 'example.style.ColorsScreen'},
    {title: 'Shadows (iOS)', tags: 'shadow', screen: 'example.style.ShadowsScreen'},
  ],
  Components: [
    {title: 'Avatars', tags: 'avatar contact', screen: 'example.components.AvatarsScreen'},
    {title: 'Animated Image', tags: 'animated image', screen: 'example.components.AnimatedImageScreen'},
    {title: 'Buttons', tags: 'button cta', screen: 'example.components.ButtonsScreen'},
    {title: 'Badges', tags: 'badge', screen: 'example.components.BadgesScreen'},
    {title: 'Cards', tags: 'cards feed', screen: 'example.components.CardsScreen'},
    {title: 'Connection Status Bar', tags: 'connection status bar', screen: 'example.components.ConnectionStatusBar'},
    {title: 'Page Control', tags: 'page', screen: 'example.components.PageControlScreen'},
    {title: 'Form Controls', tags: 'form stepper', screen: 'example.components.FormScreen'},
  ],
  Screens: [
    {title: 'State Screen', tags: 'empty state screen', screen: 'example.screens.EmptyStateScreen'},
    {title: 'Loading Screen', tags: 'loading screen', screen: 'example.screens.LoadingScreen'},
  ],
  // General: [
  //   {title: 'Form Screen', description: 'Text Input, Stepper, Select', tags: 'text input multi select email validation', screen: 'example.FormScreen'},
  //   {title: 'Feed Screen', tags: 'cards', screen: 'example.FeedScreen'},
  //   {title: 'Action Buttons Screen', screen: 'example.ActionButtonsScreen'},
  //   {title: 'Toast Button Screen', tags: 'toast floating undo button', screen: 'example.ToastButtonScreen'},
  //   {title: 'Buttons Screen', tags: 'cta action button buttons', screen: 'example.ButtonsScreen'},
  //   {title: 'Empty State Screen', screen: 'example.EmptyStateScreen'},
  //   {title: 'Loader Screen', screen: 'example.LoaderScreen'},
  //   {title: 'Default Feedback Screen', screen: 'example.FeedbackScreen'},
  //   {title: 'No Results Screen', screen: 'example.NoResultsScreen'},
  //   {title: 'Chat Screen', description: 'Messages, Images, Activities...', screen: 'example.ChatScreen'},
  //   {title: 'Top Tabs and Search Screen', screen: 'example.TopTabsScreen'},
  // ],
  List: [
    {title: 'Basic List', tags: 'basic list', screen: 'example.lists.BasicListScreen'},
    {title: 'Conversation List', tags: 'list conversation', screen: 'example.lists.ConversationListScreen'},
    {title: 'Grid List', tags: 'list grid', screen: 'example.lists.GridListScreen'},
    // {title: 'Basic List', description: 'Orders', screen: 'example.ItemsListBasicScreen'},
    // {title: 'Basic List', description: 'Hotel', screen: 'example.ItemsListBasicHotelScreen'},
    // {title: 'Contacts List', tags: 'conversations chat engage', screen: 'example.ItemsListContactScreen'},
    // {title: 'Grid List', tags: 'stores', screen: 'example.ItemsListGridScreen'},
    // {title: 'Block List', tags: 'blog bookings', screen: 'example.ItemsListBlockScreen'},
    // {title: 'Menu List', tags: 'settings entry', screen: 'example.ItemsListMenuScreen'},
    // {title: 'Action Items List Contacts', screen: 'example.ActionItemsListBasicScreen', overrideBackPress: Constants.isAndroid},
    // {title: 'Selectable Contacts List', screen: 'example.ItemsListSelectableContactScreen'},
  ],
  // Errors: [
  //   {title: 'Default Error', screen: 'example.DefaultErrorScreen'},
  //   {title: 'Custom Error', screen: 'example.CustomErrorScreen'},
  //   {title: 'Error Component', screen: 'example.DefaultErrorComponentScreen'},
  //   {title: 'Custom Error Component', screen: 'example.CustomErrorComponentScreen'},
  //   {title: 'Connection Status', screen: 'example.ConnectionStatusBarScreen'},
  // ]
};
