import React from 'react';
import { StyleProp, ViewStyle } from 'react-native';
declare const _default: React.ForwardRefExoticComponent<Omit<import("./Thumb").ThumbProps, "ref"> & {
    value?: number | undefined;
    minimumValue?: number | undefined;
    maximumValue?: number | undefined;
    initialMinimumValue?: number | undefined;
    initialMaximumValue?: number | undefined;
    step?: number | undefined;
    minimumTrackTintColor?: string | undefined;
    maximumTrackTintColor?: string | undefined;
    renderTrack?: (() => React.ReactElement<any, string | React.JSXElementConstructor<any>> | React.ReactElement<any, string | React.JSXElementConstructor<any>>[]) | undefined;
    onValueChange?: import("./types").SliderOnValueChange | undefined;
    onSeekStart?: (() => void) | undefined;
    onSeekEnd?: (() => void) | undefined;
    onReset?: (() => void) | undefined;
    containerStyle?: StyleProp<ViewStyle>;
    trackStyle?: StyleProp<ViewStyle>;
    disabled?: boolean | undefined;
    useRange?: boolean | undefined;
    useGap?: boolean | undefined;
    onRangeChange?: import("./types").SliderOnRangeChange | undefined;
    disableRTL?: boolean | undefined;
    accessible?: boolean | undefined;
    testID?: string | undefined;
    migrate?: boolean | undefined;
    enableThumbShadow?: boolean | undefined;
    disabledThumbTintColor?: string | undefined;
    throttleTime?: number | undefined;
} & React.RefAttributes<any>>;
export default _default;
